# Generated by Django 4.2 on 2025-12-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agro_App', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_document',
            field=models.FileField(upload_to='documents/id/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='land_document',
            field=models.FileField(upload_to='documents/land/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(upload_to='documents/profiles/'),
        ),
    ]
