# Generated by Django 4.2 on 2025-12-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agro_App', '0004_alter_profile_address_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
