# Generated by Django 4.2 on 2025-12-03 19:37

import Agro_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agro_App', '0005_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_document',
            field=models.FileField(upload_to=Agro_App.models.rename_id_document),
        ),
        migrations.AlterField(
            model_name='profile',
            name='land_document',
            field=models.FileField(upload_to=Agro_App.models.rename_document),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
