# Generated by Django 4.2 on 2025-12-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('profile_pic', models.ImageField(default='default.png', upload_to='student_profiles/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
