# Generated by Django 4.2 on 2025-12-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(default='Student', max_length=20),
        ),
    ]
